[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.35.1"
proto = {path = "../proto"}
tonic = "0.10.2"
hyper = "1.1.0"
bytes = "1.5.0"
thiserror = "1.0.56"
